services:
  db:
    image: postgres:17
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-startup-scripts:/docker-entrypoint-initdb.d
